# Generated by Django 4.2.30 on 2026-07-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_answer_is_accepted'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_accepted', True)), fields=('question',), name='unique_accepted_answer_per_question'),
        ),
    ]
