# Generated by Django 4.2.30 on 2026-07-13 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('GOVERNMENT', '정부'), ('FINANCE', '금융'), ('MEDICAL', '의료'), ('LIFE', '생활'), ('ETC', '기타')], max_length=20)),
                ('visibility', models.CharField(choices=[('PUBLIC', '공개'), ('PRIVATE', '비공개')], default='PUBLIC', max_length=10)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuideScrap',
            fields=[
                ('id', models.BigAutoField(auto_d=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraps', to='guides.guide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuideLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='guides.guide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='guides/')),
                ('description', models.TextField(blank=True, help_text='단계별 설명')),
                ('is_baked', models.BooleanField(default=False, help_text='이미지 가공 여부')),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='guides.guide')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='guidescrap',
            constraint=models.UniqueConstraint(fields=('user', 'guide'), name='unique_guide_scrap'),
        ),
        migrations.AddConstraint(
            model_name='guidelike',
            constraint=models.UniqueConstraint(fields=('user', 'guide'), name='unique_guide_like'),
        ),
        migrations.AddConstraint(
            model_name='guideimage',
            constraint=models.UniqueConstraint(fields=('guide', 'display_order'), name='unique_guide_image_order'),
        ),
    ]
