# Generated by Django 4.2.30 on 2026-07-13 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('families', '0001_initial'),
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family_relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide_shares', to='families.familyrelation')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='guides.guide')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_guide_shares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='guideshare',
            constraint=models.UniqueConstraint(fields=('guide', 'recipient'), name='unique_guide_share_recipient'),
        ),
    ]
