# Generated by Django 4.2.30 on 2026-07-13 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_answer_is_accepted'),
        ('guides', '0002_guideshare_guideshare_unique_guide_share_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='source_answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_guide', to='questions.answer'),
        ),
    ]
