# Generated by Django 4.2.30 on 2026-07-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_guide_source_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='guides/'),
        ),
    ]
