# Generated by Django 4.2.30 on 2026-07-13 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('GOVERNMENT', '정부'), ('FINANCE', '금융'), ('MEDICAL', '의료'), ('LIFE', '생활'), ('ETC', '기타')], max_length=20)),
                ('visibility', models.CharField(default='public', max_length=10)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='guides/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='guides.guide')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('guide', 'display_order')},
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_type', models.CharField(max_length=50)),
                ('x_ratio', models.DecimalField(decimal_places=6, max_digits=7)),
                ('y_ratio', models.DecimalField(decimal_places=6, max_digits=7)),
                ('width_ratio', models.DecimalField(decimal_places=6, max_digits=7)),
                ('height_ratio', models.DecimalField(decimal_places=6, max_digits=7)),
                ('annotation_text', models.CharField(blank=True, max_length=500)),
                ('display_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guide_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='guides.guideimage')),
            ],
        ),
    ]
