# Generated by Django 4.2.30 on 2026-07-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='description',
        ),
    ]
