# Generated by Django 4.2.30 on 2026-07-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideimage',
            name='image',
            field=models.ImageField(upload_to='guides/'),
        ),
    ]
