# Generated by Django 4.2.30 on 2026-07-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerimage',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='questionimage',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
